import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/global/Header/Header";
import Sidebar from "@/components/global/sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        <div className="flex flex-col sm:flex-row gap-2 max-w-6xl p-2 mx-auto">
          <Sidebar />
          <main className="basis-full ">{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
